version: 2
updates:
  - package-ecosystem: gomod # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: weekly
    reviewers:
      - braswelljr
    assignees:
      - braswelljr
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - braswelljr
    assignees:
      - braswelljr
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
